### ISSUE TITLE
Wrong Keypad height for dictation

### ISSUE THREAD

**Issue by fermoya** [forcedotcom/ServiceSDK-iOS#10]
Hi,

I'm using release "208.6.0" and I have this issue when I have the chat open and try to dictates. The error is clear and it's due to the keypad height that has changed from ios10 to ios11. I'm attaching screenshots taken in iPhones, I haven't tried with iPads but it must happen the same. What you can see in iOS 11 is the viewcontroller that presents the chat, the framework pushes the chat view up so that it doesn't overlap with the keypad but it does it too much, so the user can see what it's behind. This doesn't happen with iOS 10.

**iOS10**
![ios10](https://user-images.githubusercontent.com/11335612/33370212-29beb840-d4f7-11e7-80e6-4f1126a2eaae.PNG)

**iOS11**
![ios11](https://user-images.githubusercontent.com/11335612/33370384-adafedae-d4f7-11e7-9a71-734300097ba3.png)

Kind Regards,
Fernando

**Comment by sfyz** [comment]
Thanks for the detailed information @fermoya. Passing it along to the dev team.

**Comment by sfyz** [comment]
@fermoya Sorry for the delay. The latest SDK release (212.0.1) fixes this issue.  https://github.com/forcedotcom/ServiceSDK-iOS/releases
