### ISSUE TITLE
Unable to use the SDK in Xamarin project. 

### ISSUE THREAD

**Issue by PrvnKmr** [forcedotcom/ServiceSDK-iOS#100]
Hi,

I am trying to use the SDK in a Xamarin forms project. I added the framework into a Binding library and was able to work on it. But for releasing the app, the prepare-framework script has to be executed, and I am not sure about how to do this. No documentation is also found regarding the same. 

When I try building an App for distribution, it shows error **The ServiceSDK frameworks have not been prepared for release.
Please ensure the "prepare-framework" script is run *after* the "Embed Frameworks" build phase.**

Please help!! 

Thanks

**Comment by aeisses** [comment]
Hey PrvnKmr,

We have not looked into the Xamarin IDE. There should be an option somewhere in IDE to execute scripts during the build process. You would have to look that up. You can run the "prepare_framework" script at any time, it just strips the simulator and some development headers out of the framework. You could just do it on the command line.

Thanks,
Aaron

**Comment by PrvnKmr** [comment]
@aeisses 

Thanks for your quick reply..

I have tried running this script from the application (which uses the library which in turn refers the SDK) while build, but unfortunately the warning still shows up in the console for release configuration. I am sure there is something which I am missing out, but can't find it out. 

Thanks,

Praveen

**Comment by aeisses** [comment]
@PrvnKmr 

The warning always shows in the console. It is just a reminder to run the script. Once you try and submit to the app store, if the app is rejected then you know the script failed to run.

Aaron
