### ISSUE TITLE
Live Chat  'Chat with an Agent' button enabled without selecting a query

### ISSUE THREAD

**Issue by geoo993** [forcedotcom/ServiceSDK-iOS#101]
### Issue description
The Live Chat screen has the 'Chat with an Agent' button enabled without any query provided.  The button is enabled even when the user has not selected an option from the 'Query type' drop down menu and has not typed a query in 'Enter query below' textfield.

The odd thing is that Android does have the correct behaviour where the 'Chat with an Agent' button is disabled when no query is provided.

### Reproduction steps
- Download the Quidco app from the App Store.
- Login or Sign up (user has to be authenticated)
- Go to 'Support' tab
- In the list of options, select 'Live Chat'

### Version of SDK components being used
SDK version 220.1.0 - May 2019 Patch Release 

### Device(s) and version(s) of iOS being used
Most likely all iOS devices, but this has been tested on iPhone X, iPhone XR, iPhone 6 Plus, iPad Air.

### Screenshots / Videos
![IMG_0075](https://user-images.githubusercontent.com/14023259/63326157-89855880-c323-11e9-87c1-0f8cd9984aea.png)
![IMG_0014](https://user-images.githubusercontent.com/14023259/63326550-66a77400-c324-11e9-80ae-554411b4fcc3.png)

**Comment by aeisses** [comment]
@geoo993 

The fields in the pre chat have an option to when setup in code have a 'required' options. That needs to be turned on for the PreChatObjects that you want required before the "Chat with an Agent" button is turned on.

You need to checked to make sure you have the 'required' value turn on for the query input field.

Thanks,
Aaron
