### ISSUE TITLE
Fatal Crashes - Keychain

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-iOS#104]
### Issue description
Over 8000 crashes in last 7 days, for iOS users mostly on 2.17.0 and 2.17.1, with Fatal Exception: com.salesforce.security.keychainException 

We are seeing an extremely large spike in iOS crashes that are apparently caused by the SF Mobile SDK trying to read sensitive information from the keychain. Our iOS dev team has investigated and their initial conclusion is because of the current permission level the phone won’t allow it and as result the app will crash. 

### Reproduction steps
It is unknown exactly what the customer experience is, other than fatal crash. We are not sure if the crash is “only” happening in the background app state, or if this is foreground. Regardless, we would like to solve the issue quickly as possible.

### Version of SDK components being used
218.0.1

### Device(s) and version(s) of iOS being used
All Devices

**Comment by aeisses** [comment]
@geekandt Thanks for bringing this to our attention. 

Which SDK are you using?
What does 2.17.0 and 2.17.1 mean, those are not release numbers?

Thanks,
Aaron

**Comment by geekandt** [comment]
@aeisses  apologies, 2.17.0 and 2.17.1 is our app build version
Attaching the stack trace here.
Hope this helps. 

Thanks,
Gee
[iOS Fatal Crash - 2019-08-26 - SF SDK.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/3572465/iOS.Fatal.Crash.-.2019-08-26.-.SF.SDK.txt)

**Comment by aeisses** [comment]
Hey @geekandt 

Glad those are your numbers, I did not recognize them.
Which one of our SDK's are you using? Chat, SOS, Case, or KB?
Are you using the MobileSDK to authenticate users in your app?

Thanks,
Aaron

**Comment by aeisses** [comment]
Hey @geekandt 

Can you send me an entire crash report? The one you sent me just had a the thread containing the crash.

Thanks,
Aaron

**Comment by geekandt** [comment]
@aeisses  will ask our devs. I'll get back to you on this.
Thanks!

**Comment by geekandt** [comment]
@aeisses Kindly see attached for the entire crash report.
Also the .png screenshot too for context of what Crashlytics looks like.
![Crashlytics](https://user-images.githubusercontent.com/43869408/64314633-4218f080-cfe2-11e9-8ac2-47e520b6a992.png)
[iOS SF Fatal Crash - 2019-08-26 - All Threads.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/3577583/iOS.SF.Fatal.Crash.-.2019-08-26.-.All.Threads.txt)

Also, our devs have the following questions:
1. Is it possible to remove the SDK's dependency on the keychain?
2. Is it possible to change the security level so that the SDK can access the keychain in background state?
3a. What is the Silent Notification from SF generally used for? What purpose does it serve?
3b. If possible, while the app is backgrounded, would it help if the app ignore the Silent Notification from SF (or have the app "do nothing" should it receive a SF-generated Silent Notification), provided there is no adverse flow-on UX impact.

**Comment by geekandt** [comment]
> Hey @geekandt
> 
> Glad those are your numbers, I did not recognize them.
> Which one of our SDK's are you using? Chat, SOS, Case, or KB?
> Are you using the MobileSDK to authenticate users in your app?
> 
> Thanks,
> Aaron

We are using the **Case SDK**.

**Comment by geekandt** [comment]
> Hey @geekandt
> 
> Glad those are your numbers, I did not recognize them.
> Which one of our SDK's are you using? Chat, SOS, Case, or KB?
> Are you using the MobileSDK to authenticate users in your app?
> 
> Thanks,
> Aaron

Hi Aaron,
Yes, we are using the MobileSDK to authenticate users in the app.
See below:
In any case, the answer is a bit of both:
1. When a user clicks "get in touch", the app initiates authentication via Mobile SDK
2. There is a callback URL which SF provides the app, the authentication URL
3. At this point we send the URL to a webview and pass in the user credentials (the credentials are stored and returned via our backend system)
4. If all goes well, the webview then authenticates the user and the user can now create an authenticated case

Regards,
Gee

**Comment by aeisses** [comment]
Hey @geekandt 

The library where the crash is being shown is in the MobileSDK. SalesforceSDKCore is a MobileSDK library. Did your dev team recently upgrade the MobileSDK? You should open a bug with them at this repo: https://github.com/forcedotcom/SalesforceMobileSDK-iOS

You might also have to open an issue with the general salesforce support: https://help.salesforce.com/support

The crash is not happening in the CaseSDK. Not much I can help you with.

Aaron
