### ISSUE TITLE
ETA on iOS13-ready release? (Live chat disappearing)

### ISSUE THREAD

**Issue by bitwit** [forcedotcom/ServiceSDK-iOS#106]
Hi, I see that you've already acknowledged that the latest release does not function with Beta so I'm not sure whether any issues we are having come as a surprise to you. Our issue is specific to live chat, but we were going to try the first iOS13-ready release before posting a bug report.

In any case, here's a summary of our specific issue, should it not already be reported:

### Issue description
We are seeing that the live chat bubble appears then disappears a moment later, but the logs continue to show a functional chat session. iOS 13 beta only, latest SDK works fine for iOS12

### Reproduction steps
Launch a chat session on iOS13

### Version of SDK components being used
218.0.1 and 220.1.0 were both tested for this issue

### Device(s) and version(s) of iOS being used
iOS 13 beta on simulator and device

### Screenshots / Videos
Nothing to show. The chat bubble appears functional momentarily then disappears. The debug logs show a connected agent attempting to communicate

**Comment by aeisses** [comment]
Hey @bitwit,

We are aware of this issue with iOS 13. Apple made changes to the way iOS 13 handles presentedViewControllers. We are working on a fix. Not sure yet when it will be released.

As you mention this does not affect iOS 12 built projects.

Aaron

**Comment by chrisperkins** [comment]
@aeisses, 

I am experiencing issues with iOS SDK 12 built apps when running under iOS 13.1b2 (my latest attempt). I can duplicate it in the sample as well. Here is an example when using Knowledge in the sample app:

1. Accessing Knowledge displays categories but will not display individual articles when using the sample app. Pressing on an article in the displayed categories shows the buttons/window tint gradient over the category display but will not display articles. There is no way to exit this state without force-killing the app.

Example image of issue using ServiceSDK 220.1.0 on iOS 13.1b2/iPhone 7 Plus:

![ServiceSDK sample 220 1 0:iOS 13 1b2](https://user-images.githubusercontent.com/1349921/64555156-9a593680-d2f1-11e9-8bd2-f0ad07c778b3.jpeg)


Example image of correct functionality using ServiceSDK 220.1.0 on iOS 12.4 (sim)/iPhone 7 Plus:

![ServiceSDK sample 220 1 0:iOS 12 4 (sim)](https://user-images.githubusercontent.com/1349921/64556002-65e67a00-d2f3-11e9-8aa2-af248acd47bb.png)


Example of the issue using a production app built on iOS SDK 12 on iOS 13.1b2/iPhone 7 Plus:

![Prod app 220 1 0:iOS SDK 13 1b2](https://user-images.githubusercontent.com/1349921/64555409-1b183280-d2f2-11e9-8dbd-9ee128632fcc.jpeg)


Log data for sample app built with SDK 220.1.0 running on iOS 13.1b2:

```
objc[424]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1f98978a0) and /private/var/containers/Bundle/Application/3E0FF776-4611-4EA5-A7C3-20DE53870AA6/SnapinsSDKExample.app/Frameworks/ServiceSOS.framework/ServiceSOS (0x103150830). One of the two will be used. Which one is undefined.
2019-09-09 10:36:56.920956-0700 SnapinsSDKExample[424:14910] The ServiceSDK frameworks have not been prepared for release.
Please ensure the "prepare-framework" script is run *after* the "Embed Frameworks" build phase.
For more information, consult the documentation here: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/3E0FF776-4611-4EA5-A7C3-20DE53870AA6/SnapinsSDKExample.app/Frameworks/ServiceKnowledge.framework/Knowledge.momd/Knowledge.omo'
2019-09-09 10:36:57.507900-0700 SnapinsSDKExample[424:14910] [error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
2019-09-09 10:36:57.508153-0700 SnapinsSDKExample[424:14910] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: warning: Property 'customAttributes' on Entity 'CaseDetail' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
CoreData: warning: Property 'categories' on Entity 'ArticleQuery' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
2019-09-09 10:36:57.737702-0700 SnapinsSDKExample[424:14910] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'sf.SnapinsSDKExample'
2019-09-09 10:36:57.738141-0700 SnapinsSDKExample[424:14910] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'sf.SnapinsSDKExample'
CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/3E0FF776-4611-4EA5-A7C3-20DE53870AA6/SnapinsSDKExample.app/Frameworks/ServiceKnowledge.framework/Knowledge.momd/Knowledge.omo'
CoreData: warning: Property 'customAttributes' on Entity 'CaseDetail' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
CoreData: warning: Property 'categories' on Entity 'ArticleQuery' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
```


Log data for sample app built with SDK 220.1.0 running on iOS 12.4:

```
objc[39070]: Class RTCCVPixelBuffer is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x118891160) and /Users/chris/Library/Developer/CoreSimulator/Devices/0278F24E-AB32-4417-985F-FDFF7034D48C/data/Containers/Bundle/Application/4779E706-83BD-4939-87E9-9BACC56FA930/SnapinsSDKExample.app/Frameworks/ServiceSOS.framework/ServiceSOS (0x1062e0110). One of the two will be used. Which one is undefined.
2019-09-09 10:43:55.411581-0700 SnapinsSDKExample[39070:5176442] The ServiceSDK frameworks have not been prepared for release.
Please ensure the "prepare-framework" script is run *after* the "Embed Frameworks" build phase.
For more information, consult the documentation here: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm
2019-09-09 10:43:55.518818-0700 SnapinsSDKExample[39070:5176442] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2019-09-09 10:43:55.951967-0700 SnapinsSDKExample[39070:5176442] [framework] CUIThemeStore: No theme registered with id=0
2019-09-09 10:44:15.200542-0700 SnapinsSDKExample[39070:5176442] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/chris/Library/Developer/CoreSimulator/Devices/0278F24E-AB32-4417-985F-FDFF7034D48C/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-09-09 10:44:15.200796-0700 SnapinsSDKExample[39070:5176442] [MC] Reading from private effective user settings.
```

Logs attached for your diffing convenience:

[Service SDK 220.1.0 log comparison for iOS 12 SDK on 13.1b1 & iOS 12.4.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/3591975/Service.SDK.220.1.0.log.comparison.for.iOS.12.SDK.on.13.1b1.iOS.12.4.txt)


Any help would be appreciated if there is a known work-around or any obvious error on my part.

**Comment by aeisses** [comment]
Hey @chrisperkins

I have not seen that issue, but I will take a look a little deeper and get back to you.

Aaron

**Comment by bitwit** [comment]
Just to be clear the live chat disappearance issue does affect ios13 users
even if the app is built targeting the ios12 sdk, so we are anticipating
issues as soon as ios13 goes live. We’ll know exactly what day that is
tomorrow! 🔑📝

Thanks

**Comment by aeisses** [comment]
@bitwit We have not seen that in our testing.
If we have an app build with iOS 12 or before we do see the chat window disappearing when running on iOS 13.
This should not effect existing apps, can you check on your end again. You should be able to take an app built with Xcode 10 and see no issue running on an iOS 13 device.

Thanks,
Aaron

**Comment by ddorizy** [comment]
Hello,
Any update on the ETA? Now that iOS 13 has been released, it would be great to be able to build apps with the iOS 13 SDK.
Thank you

**Comment by aeisses** [comment]
Hey @ddorizy,

Our estimated release date for an iOS 13 update will be in October, the final date has not be nailed down yet.

Thanks,
Aaron
