### ISSUE TITLE
Prechat say Agent is diable, but my agent is connect

### ISSUE THREAD

**Issue by salvattore315** [forcedotcom/ServiceSDK-iOS#109]
Hello, I am not very sure if this is an issue, but when I init the chat with pre-chat a label always say the agent is disable and my agent is connect, could you help me with this?
![Simulator Screen Shot - iPhone 5s - 2019-09-23 at 15 25 03](https://user-images.githubusercontent.com/17118012/65460352-48e39800-de17-11e9-85e4-57d18409c153.png)

**Comment by aeisses** [comment]
Hey @salvattore315,

You have four required fields in your prechat. They are identified by the '*'. Until these fields are filled out the button will allow you to chat with an agent. This is configured by you when you setup the prechat.

Thanks,
Aaron
