### ISSUE TITLE
App rejected on iTunes connect due to LLVM (212.0.0)

### ISSUE THREAD

**Issue by erJohn84** [forcedotcom/ServiceSDK-iOS#14]
Hi, i have been trying to upload an app build with the latest version of ServiceSDK (212.0.0) and keep getting rejected because of LLVM instrumentation. Followed the docs from you sdk and the documentation from Apple for LLVM issues with no luck.

Have also been checking checking some forums and found out that you had this kind of issue in previous versions, could this be something that needs to be fixed in your end? maybe some flags that need to be switched off?

**Comment by sfyz** [comment]
@erJohn84 Hi. Thanks for the note. We're looking into this issue and we'll follow up shortly.

**Comment by sfyz** [comment]
@erJohn84 We're hoping to have a fix for this issue tomorrow.

**Comment by erJohn84** [comment]
Thanks a lot!

**Comment by aeisses** [comment]
@erJohn84 We have update to a 212.0.1 release. The issue with LLVM has now been fixed. Can you download the latest version and try again?
Sorry for the inconvenience.

**Comment by sfyz** [comment]
https://github.com/forcedotcom/ServiceSDK-iOS/releases
