### ISSUE TITLE
How to make Snap Ins work in the Vlocity mobile app

### ISSUE THREAD

**Issue by vbm-mobile** [forcedotcom/ServiceSDK-iOS#19]
We have attempted to set up Snap-Ins in the Vlocity mobile app (which is a managed hybrid app) by adding the desktop functionality we built for Snap-Ins to a Visualforce page and accessing that from the mobile app. While the app can pick up when an expert is available, the request to chat with an expert is not picked up by the agent, as it does on desktop. Are there any considerations needs to work through for the mobile app? And is there a recommended way to make it work in a mobile app?

We cannot use the Salesforce mobile SDK because we are using Vlocity, which is a managed package hybrid mobile app. My question is how we can use the mobile web snap-ins and get it to work on this mobile application.

What functionality are you unable to perform?
Use snap-ins in a mobile app
How many users are impacted?
Go Live Users
Is there currently a workaround in place?
No
Is there a pending deployment / go live?
Yes

**Comment by sfyz** [comment]
Hi @vbm-mobile -- I believe you're asking about Snap-ins for Web. This repository is meant for Snap-ins for iOS apps. Here are some links that might help you find an answer:

* [Snap-ins for Web success community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000Pbvt)
* [Snap-ins for Web help topic](https://help.salesforce.com/articleView?id=snapins_chat_overview.htm&type=5)
* [Snap-ins for Web dev guide](https://developer.salesforce.com/docs/atlas.en-us.snapins_web_dev.meta/snapins_web_dev/snapins_web_overview.htm)

**Comment by vbm-mobile** [comment]
At the recommendation of a Salesforce Support engineer, I am asking this question here:

Is it possible to use web snap-ins on a VF page on a mobile client?

**Comment by sfyz** [comment]
This team doesn't know anything about Snap-ins for Web. This repo is solely focused on the iOS SDK. Who is the Support Engineer who told you to post here? Maybe I can reach out to them and help find the appropriate venue?

**Comment by vbm-mobile** [comment]
Hi. Chris Banks, a Salesforce support engineer, asked that I post my questions here. I am aware this is for the iOS SDK so I appreciate you reaching out to find someone who can help on this.

**Comment by ashand-sf** [comment]
Hi @vbm-mobile - 

Which SDK are you currently trying to integrate?

**Comment by vbm-mobile** [comment]
Hi @ashand-sf. Using Snap Ins for Web and we are trying to integrate it into the Vlocity mobile app. https://developer.salesforce.com/docs/atlas.en-us.snapins_web_dev.meta/snapins_web_dev/snapins_web_overview.htm

**Comment by ashand-sf** [comment]
This is the team that supports native SDK integration.

**Comment by vbm-mobile** [comment]
I understand that - my support engineer directed me to post the question here, but it's clear this question is going in circles. I'm going to reach out to the support engineer directly.
