### ISSUE TITLE
ChatCore causes app export issues

### ISSUE THREAD

**Issue by aeioliu** [forcedotcom/ServiceSDK-iOS#2]
hi there - we are using ServiceSDK in our mobile iOS application. we rely on enterprise deployment through xcode for our internal app and we are running into the error below while exporting an archived build with `rebuild from bitcode` enabled during export. The export will complete properly if `rebuild from bitcode` is disabled, but we would prefer to have this enabled.

do you guys have any ideas as to what causes this or what a potential fix might be? thanks in advance.

<img width="574" alt="screen shot 2017-03-29 at 2 09 56 am" src="https://cloud.githubusercontent.com/assets/17889873/24447377/990911c0-1425-11e7-9b52-1d127b2266d3.png">

**Comment by aeioliu** [comment]
@sfyz

**Comment by sfyz** [comment]
Hi @aeioliu. Sorry for the delay! Let me check with the development team and follow up. You can also reach the team at the Google+ community here: https://plus.google.com/communities/104189600084591024148

**Comment by sfyz** [comment]
@aeioliu It looks like you'll need to get a hold of a bitcode-enabled version of our SDK. Please contact the product manager Rob Christensen by email: `rob.christensen [at] salesforce.com`. Sorry for the inconvenience.
