### ISSUE TITLE
Chat availability

### ISSUE THREAD

**Issue by miguel-duarte** [forcedotcom/ServiceSDK-iOS#21]
I'm developing a mobile app using React Native to be used on Android and IOS devices. In this application I'm using the Salesforce Live Agent snapin feature. The active agent is working fine and we can establish the chat with the agents, but it is not possible to check if the agent is available or not before clicking in the chat button. When we try to use your solution to check agent availability, we receive an unavailable result.

In this developments we are using:
"react": "16.0.0",
"react-native": "0.50.4",
"salesforcemobilesdk-ios": "v5.3.0"
com.salesforce.service:servicesdk:212.+

Note: I've even tried to upgrade these versions but with the same result.
"react": "16.2.0",
"react-native": "0.53.3",
"salesforcemobilesdk-ios": "v6.1.0"
com.salesforce.service:servicesdk:212.+

**Comment by sfyz** [comment]
Hi @miguel-duarte -- I passed this along to the dev team. They are out of the office today but will follow up shortly...

**Comment by sfyz** [comment]
Closing based on conversation related to the [Android issue](https://github.com/forcedotcom/ServiceSDK-Android/issues/53).
