### ISSUE TITLE
LiveChat textField bar is floating above the keyboard

### ISSUE THREAD

**Issue by paulanatoleclaudot-betclic** [forcedotcom/ServiceSDK-iOS#23]
Hello Salesforce, 

We have found an issue on the ServiceSDK on iOS, only on the new iPhone X.
This is related to the chat screen. As you will see on the following screenshots, the textField for sending message to the chat is navigating above the keyboard in a strange way.

Best,
Paul-Anatole

![simulator screen shot - iphone x - 2018-05-29 at 16 24 45](https://user-images.githubusercontent.com/39692798/40665646-01d5e6e6-635e-11e8-9fa5-d9088449f8fa.png)
![simulator screen shot - iphone x - 2018-05-29 at 16 25 45](https://user-images.githubusercontent.com/39692798/40665647-01f1f8fe-635e-11e8-8464-5814f9d853ce.png)

**Comment by AndrewBestbier** [comment]
Hi @aeisses,

I am also experiencing the same issue - do you know when you will possibly be releasing the new version? Or is there a beta version we can hook into?

**Comment by ashand-sf** [comment]
Hi @AndrewBestbier - Are you still experiencing this issue with the recent release?
