### ISSUE TITLE
Unable to contact agent with VDO call feature when using iOS device

### ISSUE THREAD

**Issue by atchariyap** [forcedotcom/ServiceSDK-iOS#24]
Hello,

I have an urgent issue that need help from Salesforce who knows when will be the release of the next version of the Snap-Ins SDK released in June?

Last time we know that it will fix the iPhone 6+ screen in OpenTok 2.13.0.

We are currently have problem on production for the iOS big screen resolution and our customer's CEO is going to have a press conference about SOS to support customer service on 14/06 so we need to fix the problem that SOS lost connection and inform the date of the release to customer as soon as possible.

Thanks in advance.

Regards,
Atchariya

**Comment by atchariyap** [comment]
Hi Aaron,

Thank you for the date.

Could you please let me know the release time and timezone? So we can plan
for testing as we have only short time before 14/06.

Please also confirm if this version will solve the issue for iOS big screen
resolution.

Thank you.

Regards,

Atchariya


Atchariya  Potduang

Project Manager

I&I Consulting Group Company Limited

475 Siripinyo Building, Unit 1801, 18Fl., Si Ayutthaya Road,

Phaya Thai, Ratchathewi, Bangkok 10400 Thailand

Phone : 063-323-8463  |  Email : acp@ii.co.th <pst@ii.co.th>  |  Website :
www.ii.co.th

[image: cert_logo-SALESFORCE-PLATFORM-APP-BUILDER.png]

**Comment by aeisses** [comment]
Hey Atchariya,

We do not provide a time on 14/06 for the release. I can tell you that at the moment the release testing is happening and the release date is expected to be 14/06.

The bug you are seeing is an OpenTok bug. We are testing on OpenTok 2.14.0 and the bug appears to be gone.

Aaron

**Comment by atchariyap** [comment]
Hi Aaron,

I think you informed it is on June 12th in the previos comment.

Regards,

Atchariya

**Comment by atchariyap** [comment]
Hi Aaron,

Our customer is asking:

*is it possible to move up the released date to be within June 8th? *as we
need a couple more days for our programmer team to update the system before
send to Apple store to review the application.

Could you please let us know?

Thank you.

Regards,

Atchariya

**Comment by ashand-sf** [comment]
Hi Atchariya - 

I am Andrew the dev manager for the iOS snap-ins team. It is not possible to move our release date foreword. We have a release process that we must follow.

Thank you - let me know if there is anything else we can help with.

Andrew

**Comment by atchariyap** [comment]
Hi Andrew,

Thank you for your reply.

I would like to confirm the release date is on June, 12 and the detail of
updates for this release so I can inform customer.

Regards,

Atchariya

**Comment by atchariyap** [comment]
Hi Andrew,

Do you have any update for the release date confirmation and detail of the release?

Thank you.

Regards,

Atchariya

**Comment by ashand-sf** [comment]
Hi Atchariya - 

That is correct. This channel is for issues found in the SDK.

**Comment by ashand-sf** [comment]
If you have any questions about release dates please refer to: trust.salesforce.com

**Comment by atchariyap** [comment]
Hi Andrew,

Thank you for your confirmation. This is an issue for iOS big screen that
OpenTok already resolved but we are waiting for the release of SDK to
contain OpenTok new version so we need to know the information for the
release.

Dear MTL Team,

Salesforce has confirmed that the release date is on June, 12 ka. For the
detail of release, I only received answer that it would contain OpenTok
2.14.0 which is the latest version and will resolve iOS big screen issue.

Regards,

Atchariya
