### ISSUE TITLE
SDK documentation 'Install in Dash' button does not install doumentation

### ISSUE THREAD

**Issue by chrisperkins** [forcedotcom/ServiceSDK-iOS#32]
Attempting to install documentation in Dash using the 'Install in Dash' button fails with 'This is not a valid Dash or Xcode docset feed'. The docset feed URL 'http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/docsets/SnapinsSDK.xml' returns 404 when tested in a web browser. HTML Documentation is accessible and works correctly at 'http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/214.0/'

**Comment by MikeNachbaur** [comment]
Thanks @chrisperkins, that seems like a configuration problem when building our documentation.  I'll make sure our doc writer is made aware of this, and we'll see what we can do about it.

**Comment by sfyz** [comment]
@chrisperkins I believe I fixed the issue with the docset location. See if it works for you now...

**Comment by chrisperkins** [comment]
Yes, works perfectly, thanks!
