### ISSUE TITLE
Uploading to appstore doesn't work because of prepare-framework

### ISSUE THREAD

**Issue by tivadargyorgy** [forcedotcom/ServiceSDK-iOS#35]
I'm using the latest version of ServiceSDK/Chat (214) pod but I couldn't upload the ipa to store. 
I'm sure that the framework the problem because I tried to upload without it and it worked.
So I need help what's the problem.

Some config:
- XCode 9.2
- Swift 4.0
- Cocoapods 1.5.3

Do you guys have any idea about it?

Related log:
ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."
Return status of iTunes Transporter was 1: ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [AppName.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
\nERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

**Comment by MikeNachbaur** [comment]
Please refer to the documentation on [preparing the SDK for app store submission](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm).

**Comment by tivadargyorgy** [comment]
@MikeNachbaur Thank you so much :), I didn't notice it. I'll check it tomorrow
