### ISSUE TITLE
Live Agent Chat to search knowledge articles based on case subject

### ISSUE THREAD

**Issue by faizmokhtar** [forcedotcom/ServiceSDK-iOS#37]
Currently, on web pre-chat form, there is a way for us to link users for knowledge articles based on the subject. Eg:

```
<input type="hidden" name="liveagent.prechat.knowledgeSearch:CaseSubject" value="true" />
```

Does the current Live Agent Chat SDK have a similar feature? If not, do you have any plan to support it soon?

SDK version used: `214.0.2`

**Comment by amisha10** [comment]
@faizmokhtar : There are no plans to support searching for an article based on a field in pre-chat, in the near future. However the SDK will be supporting the ability of linking a KB article directly in the chat feed soon.
Thanks.

**Comment by faizmokhtar** [comment]
Thanks for the reply and looking forward to it. I'll close this issue. 🙂
