### ISSUE TITLE
Does the Snap-Ins SDK agent availability call check the chat button queue length?

### ISSUE THREAD

**Issue by lancecresswell1** [forcedotcom/ServiceSDK-iOS#39]
Hi,

We have implemented the Snap-Ins SDK into our mobile app to call Live Agent in Salesforce.

We have Omni-Channel setup in Salesforce and have the Overall Queue Size set on the chat button set to 2. Does the availability check in the article below check this queue length when returning the noAgentsAvailableError? The queue length seems to be ignored. If not, how do we control the queue length?

[](https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/live_agent_listen_to_events.htm?search_text=no%20agent)

Thanks
Lance Cresswell

**Comment by plangstrom** [comment]
Hello @lancecresswell1 - Can you please link to the article that you mentioned? What response do you get on the availability check and is it always the same?
