### ISSUE TITLE
Problem uploading to App Store

### ISSUE THREAD

**Issue by superarts** [forcedotcom/ServiceSDK-iOS#4]
I'm using `cocoapods`
```
source 'https://github.com/goinstant/pods-specs-public'
pod 'ServiceSDK'
```
Which installs
```
  - ServiceSDK (208.0.0):
    - ServiceSDK/All (= 208.0.0)
  - ServiceSDK/All (208.0.0)
```
And it works on simulator and device. However, I'm getting 2 problems after achieving and uploading to App Store.

1. Invalid signature
```
ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [AlmondClient.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
```
I suspect that it's caused by the script `ServiceCore.framework/prepare-framework`. I tried to delete it manually and Xcode didn't complaint again, but pretty sure this should not be the right solution.

2. No architectures in the binary
```
ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."
```
I assume that it's caused by `KnowledgeCore.framework`, `KnowledgeUI.framework`, `ChatCore.framework`, `ChatUI.framework` etc. Those frameworks sit inside the `framework` directory in `ServiceChat.frameowork` etc. and they only contain header files and `info.plist`, and seems like they are causing problem since binaries are missing. I tried to move them into `headers` and modify `modulemap` as a desperate move and not surprisingly at all, the project couldn't be compiled.

Any suggestions please? I'm using `Xcode 8` and `cocoapod 1.2.1`.

**Comment by sfyz** [comment]
I believe you need to run the `prepare-framework` script. Have you tried these instructions?
https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm

**Comment by superarts** [comment]
Thanks sfyz, I'm sorry that I missed that part of the documentation. After adding the script it works like a charm.

PS: in the same time, would you mind take a look at something like https://stackoverflow.com/questions/20072937/add-run-script-build-phase-to-xcode-project-from-podspec ?

**Comment by sfyz** [comment]
Glad it helped! I'll check out that stackoverflow conversation and pass it along to the developers.

**Comment by fermoya** [comment]
Hi,

I'm facing the same problem, I'm using release 208.6.0 and adding to the "Run Script" section on Xcode 9.0 the following line as explained:
`"$SRCROOT/NEOL/libs/ServiceCore.framework/prepare-framework"`

That's the location of the framework "ServiceCore". Nonetheless, when I archive I find the following warning:
`warning: skipping copy phase strip, binary is code signed: absolute_path_to_my_project/NEOL/libs/SalesforceAnalytics.framework/SalesforceAnalytics`

And then when I tried to upload it to the Store I find the same problems mentioned above adding this one:
`ERROR ITMS-90087: "Unsupported Architectures. The executable for NEOL STORE.app/Frameworks/CocoaLumberjack.framework contains unsupported architectures '[x86_64, i386]'."`

Any ideas of what could be wrong?

Thanks in advance

**Comment by superarts** [comment]
Haven't updated to Xcode 9.0 yet, the approach still works with release `208.6.0` for me.

**Comment by sfyz** [comment]
Sorry to hear about this issue. I'll check in with the developers.

**Comment by sfyz** [comment]
@fermoya Are you running the `prepare-framework` script as the last build step?

**Comment by fermoya** [comment]
Sorry, I was running it but before the frameworks had been embedded, I didn't know the steps where draggable and you could drag the Run Script option to place it under "Embedded Frameworks" section.

My apologies,
Regards.

**Comment by sfyz** [comment]
Great. Glad it worked out.
