### ISSUE TITLE
Chat window not closing when calling stopSession

### ISSUE THREAD

**Issue by cipriansavastre** [forcedotcom/ServiceSDK-iOS#40]
I am currently working on integrating ServiceSDK in our iOS app.
I was able to start the chat, using the provided API, but our app requires in certain situations (like signing out) to close the chat window.

However it seems that the stopSession method closes the session (the minimized chat window shows "Chat Ended"), but the window is not closed, therefore, in the case of signing out, we end up with the minimized chat window on top of login window, which is not expected for our user experience.

Is there anything that I am missing? Do you know how to fix this?

**Comment by plangstrom** [comment]
Hello @cipriansavastre - In the recent 216 release https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/216.0.0 we provide listening for the session ending and then closing the minimized chat window. Can you please upgrade and try this?

**Comment by Mourad-Aly** [comment]
Hi @plangstrom 
I've created https://github.com/forcedotcom/ServiceSDK-iOS/issues/51 as a follow-up issue after installing 216.0.0
Thanks!
