### ISSUE TITLE
Known Issue fix date?

### ISSUE THREAD

**Issue by lancecresswell1** [forcedotcom/ServiceSDK-iOS#41]
When is the known issue 'Live Agent Chat: Case creation via pre-chat entity mapping does not work when using Omni-Channel routing. Contact creation still works correctly.' going to be fixed?

There is no easy workaround for us and we have agents who spend time unnecessarily creating these Cases manually.

**Comment by ashand-sf** [comment]
Hi @lancecresswell1 - This is an issue with your org. You should reach out to support and have them create a case.
