### ISSUE TITLE
Case assignment rule doesn't work properly.

### ISSUE THREAD

**Issue by akiko-tokuhisa** [forcedotcom/ServiceSDK-iOS#42]
Hello!

Case assignment rule doesn't work properly when records are created through Snap-ins SDK, despite it works well with web-to-case or mail-to-case.

As a temporary action, I assign case owner by using an after insert workflow rule.

I would appreciate it if you could give me how to deal with this problem.

Thank you.

**Comment by akiko-tokuhisa** [comment]
In addition, we use ver 214.0.2.

**Comment by plangstrom** [comment]
Hi @akiko-tokuhisa, I recommend that you open a support case and upgrade to the latest version as it includes a fix to an issue with iOS 12 https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/214.0.3

**Comment by akiko-tokuhisa** [comment]
Thank you for your reply! I'll try the latest version.

>I recommend that you open a support case

In fact, I've already opened a support case to check if there is any setting mistake.
But they replied me to open a github issue, since this is a Snap-ins problem.

**Comment by plangstrom** [comment]
Hi @akiko-tokuhisa, can you please provide the case number of that support case and I'll look into it?
