### ISSUE TITLE
Xcode 10 archive failing on Travis (ERROR ITMS-90035: Invalid Signature)

### ISSUE THREAD

**Issue by marioradonic** [forcedotcom/ServiceSDK-iOS#43]
Hello!

We're trying to make a build for iOS12 on Travis using Xcode 10 image.
The build is failing with error:

> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Ourappname.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

I have inspected the script and found the line that should delete the script from the framework:
```
        if (-x "$framework/$script_name") {
            unlink("$framework/$script_name");
        }

```
Obviously it's failing since the script is still there in the end.
I've tried changing the `-x` operator (File is executable by effective uid/gid.) to `-e` (File exists.) and the archive was successful.
I don't know why `-x` started to return false, but I think it can't make any harm if the script attempts to delete itself even though it isn't executable.

Let me know if you need more input. We are on the latest version (214.0.3)

Cheers.

**Comment by ashand-sf** [comment]
Hi @marioradonic - Apologies for closing this. I spoke to one of our engineers and they agree that we should modify the script, we will have this updated in the next release.

**Comment by marioradonic** [comment]
Hi @ashand-sf, no worries :)
Just fyi - we didn't have this problem with Xcode 10GM, so it was most likely a bug in Xcode 10 beta 6 that required the script to be code signed.
Anyway, I agree the script still should be modified - there is no reason for it to be packaged with the app.
Cheers

**Comment by marioradonic** [comment]
Sorry, I prematurely concluded the build works. It is still failing :(
Our hotfix for now is to add a script to remove the Salesforce script :)
```
"rm \"${PODS_ROOT}/ServiceSDK/Frameworks/ServiceCore.framework/prepare-framework\"
```

**Comment by i-dama** [comment]
To help any people that might have the same issue, this is the error message we were getting when uploading to iTunes Connect:
`ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable."`

Our hotfix was to add another build script before the Salesforce script:
```
sed -i -- 's/-x "\$framework\/\$script_name"/-e "$framework\/$script_name"/g' "${PODS_ROOT}/ServiceSDK/Frameworks/ServiceCore.framework/prepare-framework"
```

**Comment by MikeNachbaur** [comment]
It appears that within Xcode 10, the "Embed Frameworks" phase now changes the executable bit which changes the behavior of the script.  Our upcoming release effectively will do the same thing as @i-dama's workaround (e.g. changing the test flag to `-e` instead of `-x`), so that is a good workaround to apply until the new SDK release is available.

**Comment by geowarsong** [comment]
@i-dama This solution helped me to build the project but while archiving it gives me Lipo error and some other signing erros for prepare-framework

**Comment by i-dama** [comment]
@geowarsong Did you make sure your hot fix script is executed before the salesforce script?

@ashand-sf Any ETA on the update? We'd like to remove the hot fix we have

**Comment by ashand-sf** [comment]
The new SDK is now available.

**Comment by fphilipe** [comment]
Is the `prepare-framework` necessary? Can't this be done in another way? ServiceSDK is the only dependency that requires a special dance, which is a bit annoying, unfortunately.

**Comment by MikeNachbaur** [comment]
@fphilipe The framework is distributed as a multi-architecture compiled framework, with both Device and Simulator architectures. iTunesConnect doesn't strip those extra architecture images out, so it needs to be done before the application is submitted to the App Store.

It is also used to strip the developer artifacts (nested framework header directories) that aren't cleaned up by Xcode during the build process.
