### ISSUE TITLE
Move to vendored_libraries

### ISSUE THREAD

**Issue by ohitsdaniel** [forcedotcom/ServiceSDK-iOS#44]
Hey there ServiceSDK team, 👋 

we are currently working on our app launch time and noticed that loading and initializing the ServiceCore frameworks takes a long time. I noticed that in your podspec, you define `vendored_frameworks` instead of `vendored_libraries`. Therefore the ServiceCore framework is always dynamically linked. 

Cocoapods 1.6.0 beta1 enables developers to use static libraries. Instead of linking frameworks dynamically on app launch, static libraries are linked statically during compile time. Static dependencies do not need to be loaded and initialized during app launch.

Here's an example of an app launch time measurement on an iPhone 8.
```
Total pre-main time: 1.2 seconds (100.0%)
         dylib loading time: 452.12 milliseconds (36.9%)
        rebase/binding time:  93.17 milliseconds (7.6%)
            ObjC setup time:  53.84 milliseconds (4.4%)
           initializer time: 622.75 milliseconds (50.9%)
           slowest intializers :
                   ServiceCore : 417.15 milliseconds (34.1%)

```
As you can see, initialising the ServiceCore framework takes roughly 0.4 seconds. It also leads to a longer dylib loading time as it's quite a big dependency.

Moving to `vendored_libraries` would enable developers to statically link the ServiceCore dependency and reduce their app launch time immensely. Would be happy to receive some feedback on this request.

Best regards,
Daniel

**Comment by ashand-sf** [comment]
Thanks for the feedback!

cc @MikeNachbaur
