### ISSUE TITLE
Symbol not found: _kSFNotificationUserInfoAccountKey

### ISSUE THREAD

**Issue by chalemic** [forcedotcom/ServiceSDK-iOS#45]
I am running into a run-time error of "Symbol not found: _kSFNotificationUserInfoAccountKey" when attempting to use the Live Agent Chat Snap-In. This error occurs as soon as I add the ServiceSDK/Chat pod to my project, without even using it.

**System**

-  High Sierra, 10.13.6
-  XCode 10 (10A255)
-  Pod version: 1.4
-  forceios version: 6.2

**Steps to reproduce**

1. Create a new iOS project with `forceios create`
1. Replace MD5_DIGEST_LENGTH with CC_MD5_DIGEST_LENGTH (Fix for error in XCode 10 with SDK 6.2 as mentioned in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2614)
1. Build and run the project. Verify it works as expected.
1. Follow directions at https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_install_sdk_cocoapods.htm#ios_sdk_install_ios_cocoapods to add Chat
  4.1 Add `source 'https://github.com/goinstant/pods-specs-public'`
  4.2 Add `pod 'ServiceSDK/Chat'`
  4.3 Run `pod install`
1. Build and run project
1. Receive run-time error
1. Remove `pod 'ServiceSDK/Chat'` from podfile, run `pod install`, and re-build project. Project works as expected.

This also happens if I manually add the Snap-Ins for ServiceCore and ServiceChat per the directions at https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_install_sdk_manually.htm

**Full error**

> dyld: Symbol not found: _kSFNotificationUserInfoAccountKey
>   Referenced from: /Users/[username]/Library/Developer/CoreSimulator/Devices/8373AB4E-AABA-4AD9-B418-648CF7DF34CB/data/Containers/Bundle/Application/2F43183B-A7B2-4AA1-9076-08622C6578EF/LiveAgentTest.app/Frameworks/SmartStore.framework/SmartStore
>   Expected in: /Users/[username]/Library/Developer/CoreSimulator/Devices/8373AB4E-AABA-4AD9-B418-648CF7DF34CB/data/Containers/Bundle/Application/2F43183B-A7B2-4AA1-9076-08622C6578EF/LiveAgentTest.app/Frameworks/SalesforceSDKCore.framework/SalesforceSDKCore
>  in /Users/mchale/Library/Developer/CoreSimulator/Devices/8373AB4E-AABA-4AD9-B418-648CF7DF34CB/data/Containers/Bundle/Application/2F43183B-A7B2-4AA1-9076-08622C6578EF/LiveAgentTest.app/Frameworks/SmartStore.framework/SmartStore
> (lldb) 

Demo project that demonstrates the issue can be found at https://bitbucket.org/chalemic/liveagenttest

**Comment by MikeNachbaur** [comment]
The Snap-ins SDK, as of 212.0.0, no longer depends upon the Salesforce MobileSDK.  Are you explicitly adding the MobileSDK to your Cocoapods?  Or are you targeting an older version of the Snap-ins SDK?

**Comment by ashand-sf** [comment]
Hi @chalemic - which version of the SDK are you using?
