### ISSUE TITLE
Receiving ChatID and CaseID via iOS SDK 

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-iOS#46]
After every chat ends, we would like to direct customer to a rating page, in which after customer has rated us, the result will be sent back to be associated with chat/case raised by customer.

To do so, caseID and chatID is needed to correctly link result and its case, however, right now the SDK only know agentID.

Any advice on how to pass caseID and chatID via SDK?

Version of Mobile SDK Used:  SDK version: 214.0.4, Live agent chat version: 1.6.2
Issue found in Native App or Hybrid App: Native

**Comment by ashand-sf** [comment]
Hi @JinTiloganart do you still need help with this?
