### ISSUE TITLE
LiveChat typing bar overlap text bubble

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-iOS#52]
1.Version of Mobile SDK Used: SDK version 214.0.4, Live agent chat version: 1.6.2
2.Issue found in Native App or Hybrid App: Native app
3. OS Version: 12.0.1
4. Device: iPhone X
5. Steps to reproduce:
1) Customer initiate a chat from iPhone X
2) Got connected to an agent
3) Customer send a message to agent 
4) Customer click on the typing bar again
5) Keyboard pops up and overlap the message sent earlier, the message bubble is only half-shown. 

Actual behavior: Keyboard/Typing area overlap the message sent earlier
Expected Behavior: Can see the previously sent message wholly.  

------------------------------------------------------
Seems like only happen to iPhone X, tried with 6sPlus and there's no issue.

![iphonex](https://user-images.githubusercontent.com/44631258/49637993-e238ed80-fa41-11e8-80f3-eaa6553d0175.PNG)

**Comment by ashand-sf** [comment]
Hi @JinTiloganart - can you please upgrade to the 216 build of the SDK? Thank you!

**Comment by ashand-sf** [comment]
Thanks @JinTiloganart for the update. We will try and reproduce and I will get back to you.

**Comment by plangstrom** [comment]
@JinTiloganart Can you please provide a video of this because we can't reproduce it with the steps above using a iPhone X w/ iOS 12.1. The messages bubbles stay above the keyboard.

**Comment by ashand-sf** [comment]
Hi @JinTiloganart - Are you able to send us a video reproducing the issue? We are unable to reproduce here.

**Comment by JinTiloganart** [comment]
Hi @ashand-sf  and @plangstrom , I modified the video sharing setting, appreciate any update.
Thanks!

**Comment by ashand-sf** [comment]
Hi @JinTiloganart - Are you using IQKeyboardManager in your app?

**Comment by JinTiloganart** [comment]
Hi @ashand-sf - Checked with dev and we're not using IQKeyboardManager.

**Comment by JinTiloganart** [comment]
Hi @ashand-sf , to answer your question about SDK version, we're using SDK v.216.0.1
