### ISSUE TITLE
SDK Version 216.0.0 is causing our mobile app to crash in Production

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-iOS#56]
**Issue description**
The iOS version of the Mobile SDK is causing  our app to crash(authentication not working) when the SDK is pointed in Production but once it is pointed to a lower environment (Staging), it is successfully authenticating.

**Reproduction steps**
Below is the code to reproduce the issue:
https://drive.google.com/open?id=1JG3YBS9Avfvw8pgGmjNytUA_jBmE9cWQ
 
Kindly send us an email so we can send you the password on the zip file
My email is sharmaine.a.cinense@accenture.com
 
How to use the code to reproduce the issue:
1. Open TestSalesForce.xcodeproj using Xcode 10
2. Build and run the code, on the first screen, click 'Login' button

Note: App will display a list of cases, click on one of them.
Expected: See the detail messages for that case
Actual: the screen show nothing

**Version of SDK components being used**
210.0.0 is the current SDK Version being used that is working. 216 is the version that is causing the app to crash.

**Comment by ashand-sf** [comment]
Hi - This issues page is for Mobile Service SDKs.

**Comment by ashand-sf** [comment]
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues

**Comment by daricDava** [comment]
@ashand-sf  Kindly reopen this ticket as we have been referred back to your team from SalesforceMobileSDKiOS team.

Here is the thread for your reference:
[https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2733](url)

**Comment by ashand-sf** [comment]
Ok. @MikeNachbaur Are you able to take a look at this one?

**Comment by shanecinense1994** [comment]
Hi @MikeNachbaur,

Good day.
Just wanted to follow up regarding this case.
Is there any information you want us to provide on our end? Kindly let us know.
Thank you

**Comment by daricDava** [comment]
Hi @MikeNachbaur 

May we know if there are any updates. Thank you.

**Comment by daricDava** [comment]
Hi, 

Is anyone looking at ticket? We can see that there are activities on this ticket from @ashand-sf , @MikeNachbaur , and @amisha10 . We are hoping to get info regarding this. Thank you.

**Comment by MikeNachbaur** [comment]
Most of the team has been out of the office due to the holidays, so we'll be looking into this now.  My apologies for the delay in responding.

**Comment by daricDava** [comment]
Hi @MikeNachbaur,

We completely understand. Thank you for letting us know about the updates. Kindly do keep us posted if anything comes up.

**Comment by daricDava** [comment]
Hello @MikeNachbaur ,

Happy new year! How's  the holidays? May we know if there are any news on this. Thank you.

**Comment by daricDava** [comment]
Hi, @MikeNachbaur, are ther any updates?

**Comment by MikeNachbaur** [comment]
I've responded via email to ask for more information; I wanted to make sure you've received it?

**Comment by daricDava** [comment]
Hi, Thank you for the update. I’ll read the email and get back you soon.

**Comment by daricDava** [comment]
Hi @MikeNachbaur , can we set a meeting regarding the URL being queried? We have checked some things on our end and we want to clarify some things and seek aid in our analysis. Thank you.

**Comment by MikeNachbaur** [comment]
@daricDava We have a fix that that should be coming out in our next release that will resolve your issue; I've verified the fix on the test app that you sent us.

I've been traveling, but plan to respond to your email shortly.  Thank you.

**Comment by daricDava** [comment]
Hi,  hope all is well in your travels. I sent an email in the other email thread. We’ll wait for your reply.

Regards,
Daric

**Comment by daricDava** [comment]
Hi @MikeNachbaur,

Regarding our other thread, Just want to clarify the release date that was indicated by Rob is Feb-12 or Dec-02? Thank you.

**Comment by MikeNachbaur** [comment]
February 12th.
