### ISSUE TITLE
[Question] Minimizing chat window

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-iOS#61]
1.Version of Mobile SDK Used: SDK version 214.0.4, Live agent chat version: 1.6.2
2.Issue found in Native App or Hybrid App: Native app
3.OS Version: 12.0.1
4.Device: iPhone 7
5.Expected Behavior: Chat window can be minimized
6.Actual behavior: If we set defaulttominimized = false, the full chat window can't be minimized. 

----------------------------------------------------------------
Hi,

In the iOS Developer guide said that we can set defaultToMinimized to be true/false to indicate whether the chat session starts out as a minimized thumbnail view. However, if we set it as 'false' seems like the chat window won't have the minimize button, is this an expected behavior or we have to set other values to add minimize button to the chat window?

![image](https://user-images.githubusercontent.com/44631258/50878316-1cb2f300-1411-11e9-809b-c049cbde683b.png)

https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/configure_lac_session.htm

![image](https://user-images.githubusercontent.com/44631258/50878228-93032580-1410-11e9-93ad-b2a2e118c27c.png)

**Comment by aeisses** [comment]
Hey JinTiloganart,

There should be two flags, defaultToMinimization, and allowMinimization. If you have allowMinimization to true you should always be able to minimize. Can you confirm this value is set to true? (true is the default)

Note: if you have allowMinimization set to false defaultToMinimization does nothing.

Let me know,
Aaron

**Comment by JinTiloganart** [comment]
Hi @aeisses ,

Confirmed with our developer that 'allowMinimization' is set to 'True'.
Any other setting need to be adjusted? or any possible reason why the window can't be minimized? 

Thanks!
