### ISSUE TITLE
[Question] Using Einstein bot with Live Agent

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-iOS#62]
1.Version of Mobile SDK Used: SDK version 214.0.4, Live agent chat version: 1.6.2
2.Issue found in Native App or Hybrid App: Native app
3.OS Version: 12.0.1
4.Device: iPhone 7
5.Expected Behavior: Chat window can be minimized

Hi,

We're implementing Einstein bot with Live Agent SDK and would like to know:

1) Is it possible to set when user click on chat button, the Einstein bot page will be displayed in full screen without having to wait (since it's chatbot, there's no need for queuing)

We know that there's defaulttominimized property to trigger full screen by default, wondering if it applies to Einstein bot as well?

![image](https://user-images.githubusercontent.com/44631258/51522289-fc992000-1e63-11e9-92c9-9421b26df358.png)

https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/live_agent_einstein_bots.htm

2) After choosing transferr to agent from Einstein bot, if there's a queue, would user see the full queue page like image below?

![image](https://user-images.githubusercontent.com/44631258/51524532-46d0d000-1e69-11e9-82a3-0806f353f200.png)

**Comment by aeisses** [comment]
Hey JinTologanart,

Answers to your questions:
1. Chatbots screen will follow whatever value defaultToMinimized flag is set too.
2. When you transfer to an agent from a chat bot you get the following graphic in the feed. You will see the feed and be able to scroll in full screen. It does not load the full screen queue you have posted.

![file](https://user-images.githubusercontent.com/2683848/51559613-bd190680-1e58-11e9-992d-aadfef3faca3.jpg)

Thanks,
Aaron

**Comment by JinTiloganart** [comment]
Hi @aeisses , thank you for your clarfication,

a few more questions on this,

**1) Chatbots screen will follow whatever value defaultToMinimized flag is set too.**
>> If defaultToMinimized is set to 'True', would the floating bubble look the same as Live Agent's?
Or it will be different with Einstein bot? 

**2)  When you transfer to an agent from a chat bot you get the following graphic in the feed. You will see the feed and be able to scroll in full screen. It does not load the full screen queue you have posted.**
>>  Does this mean customer won't know their position in the queue at all? Is there any workaround on this? 

Thank you!

**Comment by aeisses** [comment]
Hey JinToganart,

1) If the view is minimized and a chatbot is active you will see a chatbot avatar. You as a user can replace that.
![chatbotavatar 3x](https://user-images.githubusercontent.com/2683848/51623521-43901f80-1f0f-11e9-9dd1-53d7f91b8c6c.png)

2) 1. Yes
2. Yes, as long as the session does not end.
3.  No, the feed will function like a normal feed new messages and feed information coming in at the bottom.

Thanks,
Aaron
