### ISSUE TITLE
[Question] Instance Refresh and SwitchServer

### ISSUE THREAD

**Issue by denyspro** [forcedotcom/ServiceSDK-iOS#63]
This is a generic question regarding the behavior of the SDK during an instance refresh. The [liveAgentPod config used in SCSChatConfiguration](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/live_agent_basic_setup.htm?search_text=SCSChatConfiguration(liveAgentPod ) changes when an [instance refresh](https://help.salesforce.com/articleView?id=000230807&language=en_US&type=1) happens.

Does the SDK handles the [SwitchServer](https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_response_bodies.htm#SwitchServer) response and uses the newUrl response if the config was not updated in the app after the instance refresh?

**Comment by MikeNachbaur** [comment]
Yes it does. It will automatically reconnect to the appropriate pod once the session is initiated.  That does involve an extra step on the part of the client, so it's advisable to keep your Pod configuration up to date as much as is reasonable when shipping new releases to the App Store.

**Comment by denyspro** [comment]
Thank you very much sr.!
