### ISSUE TITLE
Larger text not word wrapping

### ISSUE THREAD

**Issue by edkimdd** [forcedotcom/ServiceSDK-iOS#65]
### Issue description & Reproduction Step
If you change your text size from Settings -> Accessibility -> Larger Text -> there is a slider you can move to the right. If we increase the text size, the article titles under each category stop word wrapping which causes issues with longer strings. 

### Version of SDK components being used
214.0.4

### Device(s) and version(s) of iOS being used
iPhone 7 12.1.2 

### Screenshots / Videos
<img width="372" alt="screen shot 2019-02-01 at 4 01 15 pm" src="https://user-images.githubusercontent.com/38704323/52156064-d0875700-263a-11e9-9adb-3177a30f03d2.png">
<img width="376" alt="screen shot 2019-02-01 at 4 01 21 pm" src="https://user-images.githubusercontent.com/38704323/52156065-d0875700-263a-11e9-9f2e-563fb7c9a93c.png">

**Comment by aeisses** [comment]
Hey Edkimdd,

We are looking into this issue and will get back to you.

Thanks,
Aaron

**Comment by aeisses** [comment]
Hey Edkimdd,

We have just released a new version of the ServiceSDK, 218.0.0. It contains a fix for this issue.

Thanks,
Aaron
