### ISSUE TITLE
Time out Alert not working on Native IOS SDK

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/ServiceSDK-iOS#66]
* Version of Mobile SDK Used: SDK version 216
* Issue found in Native App or Hybrid App: Native app
* OS Version: 12.0.1
* Device: iPhone 8
* Steps to reproduce:
* In 'Chat Buttons and Automated Invitations' ,configure 'Customer Time-Out (seconds)' to 90 seconds
* Initiate chat on iOS device
* Chat got routed to agent
* Agent send message to customer
* Customer leave the app open in the foreground for 5 mins
* leave the app in the background for 5 mins
* Actual behavior: Chat session is not terminated after 5 mins of inactivity
* Expected Behavior: Chat session is termination alert after customer is inactive for 60 secs from Agent's last reply  and terminate the chat after 90secs.
* Error Log:

**Comment by aeisses** [comment]
Hey Kravuri,

Thanks for pointing this out. We are looking into this.

Thanks,
Aaron

**Comment by aeisses** [comment]
Hey Kravuri,

We took sometime to look into this issue, are you talking about the 'Customer Time-Out' setting in the org?

Thanks,
Aaron

**Comment by kravuri1987** [comment]
Yes I am about it.

**Comment by kravuri1987** [comment]
Hi Guys,

Any updates on the customer time out alerts.

**Comment by aeisses** [comment]
Hey Karvuri,

This is not a feature that is implemented on the ServiceSDK for mobile apps. We have it on our road map to implement, but the release that will include it has not been determined yet.

Thanks,
Aaron

**Comment by kravuri1987** [comment]
Hi aeisses,

What are other alternative ways of handling the inactive users .Can you please suggest? As i dont see any functions i can use to handle it on my end.

**Comment by aeisses** [comment]
Hey Kravuri987,

At the moment we do not have any functionality to perform this functionality. You could use the SCSChatEventDelegate to monitor the activity on the app. You could keep a timer in your app and end the session if it become inactive. http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/218.0/Protocols/SCSChatEventDelegate.html

Thanks,
Aaron
