### ISSUE TITLE
Unable to set images in the sdk 218.0

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/ServiceSDK-iOS#67]
We are trying to set different images using the latest 218.0. But non of them are working can you please help us.

Below is our code.
if let minimizeImage = UIImage(named: "minimize"),
            let closeImage = UIImage(named: "CloseX"),
            let chatAgentImage = UIImage(named: "AgentJoined"),
            let loadingImage = UIImage(named: "HourGlass"),
            let sendImage = UIImage(named: "Send") {
            appearanceConfiguration.setImage(minimizeImage,
                                             compatibleWithTraitCollection: minimizeImage.traitCollection,
                                             forToken: .minimizeButton)
            appearanceConfiguration.setImage(closeImage,
                                             compatibleWithTraitCollection: closeImage.traitCollection,
                                             forToken: .close)
            appearanceConfiguration.setImage(chatAgentImage,
                                             compatibleWithTraitCollection: chatAgentImage.traitCollection,
                                             forToken: .chatAgentAvatar)
            appearanceConfiguration.setImage(loadingImage,
                                             compatibleWithTraitCollection: loadingImage.traitCollection,
                                             forToken: .preChatIcon)
            appearanceConfiguration.setImage(sendImage,
                                             compatibleWithTraitCollection: sendImage.traitCollection,
                                             forToken: .send)
        }

**Comment by aeisses** [comment]
Hey Kravuri,

I think you should use the UISreen.main.traitCollection to get the trait collection for the device you are using. That should fix your issue, here is an example:
        if let minImage = UIImage(named: "MinImage") {
            serviceCloud.appearanceConfiguration .setImage(minImage, compatibleWithTraitCollection: UIScreen.main.traitCollection, forToken: .minimizeButton)
        }

Thanks,
Aaron

**Comment by kravuri1987** [comment]
Hi Aron,

Thanks aron for the fix.This worked for the most part but for the loading image it is not working.Below is my code.Please help.

if let loadingImage = UIImage(named: "HourGlass") {
            appearanceConfiguration.setImage(loadingImage,
                                             compatibleWithTraitCollection: UIScreen.main.traitCollection,
                                             forToken: .preChatIcon)
}

Thanks 
Kumara

**Comment by aeisses** [comment]
Hey Kravuri,

It worked for me, this is the line of code I used:
            serviceCloud.appearanceConfiguration .setImage(image, compatibleWithTraitCollection: UIScreen.main.traitCollection, forToken: .preChatIcon)

Can you ensure that the image "HourGlass" exists in your Assets folder? If you attempt to assign an image that does not exist with this replacement, nothing happens and you are given no information as to why.

Thanks,
Aaron
