### ISSUE TITLE
Unable to set background colors for the bankers and customers.

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/ServiceSDK-iOS#68]
Hi,

We are unable set the background color for the banker bubble and customer bubble.

appearanceConfiguration.setColor(UIColor(red: 0.33, green: 0.72, blue: 1, alpha: 1), forName: .contrastInverted).Below you can see the affected screen.Please suggest a way to set the colors safely without effecting the whole back ground.

<img width="545" alt="screen shot 2019-02-21 at 2 47 56 pm" src="https://user-images.githubusercontent.com/9764367/53207501-b6f97f80-35e8-11e9-988a-054860ca4154.png">

**Comment by aeisses** [comment]
Hey Karvuri,

This does appear to be a bug on our side. I will open a bug locally and our team will take a look at it.
I did find a work around for you, if you set the .contrastQuaternary colour, the background will be set to that colour.
 
For example: 
        serviceCloud.appearanceConfiguration.setColor(UIColor(red: 1, green: 0.00, blue: 0.00, alpha: 1), forName: .contrastInverted)
        serviceCloud.appearanceConfiguration.setColor(UIColor(red: 1, green: 1, blue: 1, alpha: 1), forName: .contrastQuaternary)
Will set the background to white and the bubble to red.

Thanks,
Aaron

**Comment by aeisses** [comment]
Hey Karvuri,

I did some digging into this bug today so it is not a bug, more it is some undocumented behavior. So on iOS only, this does not happen on Andoird, if you set the contrastSecondary or the contrastInverted colors they change the contrastTertiary and the constrastQuaternary. The following formulas determine the new color:
contrastTertiary = contrastInverted + contrastSecondary(10% opacity)
contrastQuaternary = contrastInverted + contrastSecondary (50% opacity)

So when you changed the contrastSecondary the background of the chat feed, which is contrastQuaternary color also changed. When you set the contrastQuaternary this change overrides the formula with the provided color.

We will be determining how to move forward with this issue internally.

Thanks,
Aaron

**Comment by kravuri1987** [comment]
Hi Aeisses,

Thanks for the replies.What about the send button color when we setting the contrastQuaternary it is effecting the send button completely.It is not visible at all.Can you please help and update the documentation accordingly.
