### ISSUE TITLE
"Type a message" textfield doesn't show the keypad iOS11

### ISSUE THREAD

**Issue by fermoya** [forcedotcom/ServiceSDK-iOS#7]
Hi,

I'm using the latest version of your SDK, although I've tried with older versions and the issue remains. When I launch the chat in a device running iOS 11, the textfield doesn't show the keypad when tapped upon (see in the picture, I mean the textfield whose placeholder is "Escribe aquí tu mensaje").

![img_0340](https://user-images.githubusercontent.com/11335612/31178126-686e2b94-a918-11e7-949b-e33db3d13467.PNG)

With iOS 9 and 10 this works perfectly, the only issue is in iOS 10.

Regards.

**Comment by sfyz** [comment]
Hi! This is a known issue with the [208.3 release](https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/208.3) of the SDK when using Xcode 9. We just released a patch for this problem in the [208.5 release](https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/208.5) of the SDK. You can download the latest version of the SDK from our [product page](https://developer.salesforce.com/page/SnapinsMobile), or with Cocoapods. Hope that helps!

**Comment by fermoya** [comment]
Hi,

Thanks, it truly works, sorry I wasn't paying attention at your latest releases this month.

Regards
