### ISSUE TITLE
216.0.1 Infinite loop crash in Knowledge layout: [NSISEngine _flushPendingRemovals]

### ISSUE THREAD

**Issue by chrisperkins** [forcedotcom/ServiceSDK-iOS#70]
### Issue description
The Knowledge article list appears to crash while laying out subviews in `SCSEmptySearchView` after the app is moved from foreground/background in various orientations, so far only on iPhone. The crash appears to be due to an infinite loop during the iOS view layout phase. Logs indicate that the user launches the app, views Knowledge, backgrounds and then foregrounds the app. 

This app is a predominantly Swift project. Knowledge is displayed by:

`ServiceCloud.shared().knowledge.setInterfaceVisible(true, animated: true, completion: nil)`

### Reproduction steps
Unable to determine steps to reproduce, though we are receiving crash reports every few days.

### Version of SDK components being used
216.0.1

### Device(s) and version(s) of iOS being used
iPhone 6, iOS 12.1.4
iPhone 7, iOS 12.1.2
iPhone 7 Plus, iOS 12.1.3
iPhone 6s, iOS 11.2.5

### Screenshots / Videos
N/A

[[NSISEngine _flushPendingRemovals] crash 1.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895457/NSISEngine._flushPendingRemovals.crash.1.txt)
[[NSISEngine _flushPendingRemovals] crash 2.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895458/NSISEngine._flushPendingRemovals.crash.2.txt)
[[NSISEngine _flushPendingRemovals] crash 3.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895459/NSISEngine._flushPendingRemovals.crash.3.txt)
[[NSISEngine _flushPendingRemovals] crash 4txt.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895550/NSISEngine._flushPendingRemovals.crash.4txt.txt)

**Comment by aeisses** [comment]
Hey Chris,

Thanks for sending this to us, we will take a look.

Aaron

**Comment by MikeNachbaur** [comment]
Hi @chrisperkins, I've verified the bug and was able to reproduce it locally. We're looking into it.

Thanks again for your great attention to detail in your bug reports! It's very appreciated.

**Comment by aeisses** [comment]
Hey Chris,

We will have a fix for this crash in our next release. If you continue to see it please let us know.

Aaron
