### ISSUE TITLE
Send Button Visibiltiy is getting effected

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/ServiceSDK-iOS#72]
Hi Aeisses,

Thanks for the replies.What about the send button color when we setting the contrastQuaternary it is effecting the send button completely.It is not visible at all.Can you please help and update the documentation accordingly

**Comment by aeisses** [comment]
Hey Kravuri987,

The send button is a primarySecondary color. Here is the documentation that gives some information on what colors are which. https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/customize_colors.htm

I just did a quick test and changing the contrastQuaternary does not effect the color of the send buttons. One of the tricks with branding is finding the right color combinations that work. That can be difficult and take a lot of time.

Thanks,
Aaron
