### ISSUE TITLE
How to disable a chat button on IOS if the customer is already on the screen and agent is not online?

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/ServiceSDK-iOS#74]
How to disable a chat button on IOS screen,if the customer is already on the screen and agent is not online?

**Comment by aeisses** [comment]
Hey Kravuri987,

The only option we have for checking to see if an agent is on-line is the agent availability protocol: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/live_agent_check_agent_availability.htm

You can then use this disable or enable your chat button as you choose.

Thanks,
Aaron
