### ISSUE TITLE
Salesforce SDK issue - Apple is rejecting app store submission due to 2 permissions required in SF SDK

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-iOS#75]
### Issue description
We have a Salesforce SDK issue, which we need assistance.

In short, our main issue is that Apple has rejected our app store submission due to 2 permissions required in SF SDK.  This will prevent us from incorporating the most recent versions of the Salesforce ServiceSDK. It held up our release schedule yesterday, but to get around this, we had to revert back to a lower SDK version.

Below are the detailed notes on the issue.

The latest SalesForce ServiceSDK (218.0.0) requires 2 permissions from users:
- The permission to use the microphone on the device
+ In particular: the ServiceCore framework is using AVAudioSession
- The permission to use Speech recognizer feature of the phone
+ In particular: the ServiceCore framework is using SFSpeechRecognizer
Currently, our app does not use these permissions for any functionalities in the app, and our build got rejected by Apple because in order to have these permissions. We have to deliberately ask users to grant the app the permits.

Our previous build did not encounter this issue because the old ServiceSDK (210.0.0) did not require these permissions.

So our question is: Is it possible to exclude the functionalities which require those permissions out of the latest ServiceSDK (218.0.0) or ServiceCore framework in particular?
We're not using those functionalities anywhere in our app and want to avoid prompting a user for these permissions.

### Version of SDK components being used
ServiceSDK (210.0.0)

### Device(s) and version(s) of iOS being used
all devices

**Comment by aeisses** [comment]
Hey Geekandt,

This was an oversight on our part. We implemented the voice recognition code in for a demo and moved the code into the SDK for a future release. We did not anticipate the app store submission issue.

We will remove the code and put out a patch. If we add the code back in we will put it in an optional framework.

Thanks for pointing this out and your patience as we put out a patch,
Aaron

**Comment by geekandt** [comment]
Hi @aeisses , 
Thank you for your response.
Would like to confirm if putting out the patch is completed?

Thank you.
Regards,
Gee

**Comment by aeisses** [comment]
Hey Geekandt,

We are planning on releasing a patch tomorrow.

Thanks,
Aaron

**Comment by geekandt** [comment]
Hi @aeisses ,
Thanks for confirming.
Looking forward for the release tomorrow. 

Thanks,
Gee

**Comment by aeisses** [comment]
Hey @geekandt 

The release 218.0.1 has been release. If you have any issues please reach out.

Thanks,
Aaron

**Comment by geekandt** [comment]
Thank you!

**Comment by geekandt** [comment]
Hi @aeisses ,
In the new patch 218.0.1.
We've encountered an issue.
When I receive and tap on a SF iOS push notification:

1. While app is backgrounded _OR_ app is foregrounded
*Actual:* My Queries page opens (the one with all the queries raised by customer)
*Expected:* The actual (deeper) case details page must open (with reply)

Let me know if you need more details.
Thanks,
