### ISSUE TITLE
When SF iOS push notification is received and tapped, it doesn't open the actual case

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-iOS#76]
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### Issue description
In the new patch 218.0.1.
We've encountered an issue.
When I receive and tap on a SF iOS push notification:

While app is backgrounded OR app is foregrounded
Actual: My Queries page opens (the one with all the queries raised by customer)
Expected: The actual (deeper) case details page must open (with reply)

Let me know if you need more details.
Thanks,

### Version of SDK components being used
 218.0.1

### Device(s) and version(s) of iOS being used
All iOS devices - iOS 10 and above

**Comment by MikeNachbaur** [comment]
For Case push notifications, the behavior of the SDK is to either
a) show the Case Detail if the push notification contains the case ID in a specific key;
b) show the Case List when the notification doesn't indicate which case was updated.

For more information, please refer to the documentation on configuring notifications:
https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/cases_push_notification.htm

The key is `caseid`, all lower-case.
