### ISSUE TITLE
The framework takes much time while App is loaded

### ISSUE THREAD

**Issue by lemanhtien** [forcedotcom/ServiceSDK-iOS#78]
Hi Salesforce team,
Currently, we are using 2 frameworks `ServiceCore` and `ServiceChat` in our project. As we start using these frameworks, we noticed that  our app takes much longer time to load from **Cold Start**. I know your frameworks are dynamic one, but it takes a lot of time to load.

Is there any solution for this situation? Does your team provide the static framework instead of dynamic one ?

Some information to compare:

```
Total pre-main time: 3.9 seconds (100.0%)
...
ServiceCore : 447.63 milliseconds (11.4%)
```

**Comment by aeisses** [comment]
Hey Lemanhtien,

We do not provide a static framework option. Generally the loading times increase when an app has a lot of dynamic frameworks. Apple is constantly improving on this process, but there is not much that can be done about this at the moment.

Thanks,
Aaron

**Comment by lemanhtien** [comment]
Hi @aeisses,
Thanks for your comment. We all know that using dynamic frameworks will increase loading time. But as you can see here, the point I want to mention is your only framework takes a lot of time in total (11.4%), no others framework in my app takes more time than the Salesforce one.
We can understand if your team cannot provide a static framework, but I hope your team can improve this one in the next version 

Thanks
