### ISSUE TITLE
URGENT: SF push notification is not working for auto responses when a case is created or a case is closed

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-iOS#81]
### Issue description
When a case is created using our app, there is an auto response that will be sent to the user in the app. This auto response must also have a push notification. 
But the push notification is not working for the auto response.

But the adhoc reply from Salesforce to app has push notifications. 

Only the auto responses it is not working.

This is urgent as we can't continue on the release unless this is fixed.

### Reproduction steps
Create case through the app.

### Version of SDK components being used
MobileSDK 6.2.0 + ServiceSDK 218.0.1

### Device(s) and version(s) of iOS being used
•	iPhone 7 on iOS 12.2
o	appversion: 2.14.1.3084
•	iPhone 6S+ on iOS 11.0.1
o	appversion: 2.14.1.3043
•	iPhone SE on iOS 12.2
o	appVersion 2.14.1.3070
•	iPhone 6 on iOS 12.2
o	appVersion 2.14.1.3070

**Comment by aeisses** [comment]
Hey Geekandt,

Are you using an authenticated user?

Thanks,
Aaron

**Comment by geekandt** [comment]
Hi Aaron,

Yes, we are using an authenticated user.

Regards,
Gee

**Comment by aeisses** [comment]
Hey Geekandt,

I checked with the team and it turns out we do not support this push notification on case creation.

So this would be feature request. You need to contact your Sales Engineer(SE) if you have one or go through the main Salesforce support channel: https://help.salesforce.com/home

Thanks,
Aaron

**Comment by plangstrom** [comment]
@geekandt As a workaround using the QuickAction API, you could try setting up a custom Apex trigger for the case publisher to automatically make posts on the case when the case changes status to created or closed. The posts on the case could send push notifications to the SDK just like the agent posts do.

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_quickaction_quickactionrequest.htm

**Comment by geekandt** [comment]
Hi @plangstrom , This is the current functionality in our app. We already have a custom code that will post in the case chatter feed for the open and closed cases. But, we are not receiving the push notifications for this.

Please advise?

**Comment by plangstrom** [comment]
Hi @geekandt and thanks for clarifying. Please log a customer support case for this as the case publisher and Chatter feed are not owned by the mobile Service SDK team. In the support case, describe how you have configured this, what the scenario is, and that the expected outcome is for these posts to be become notifications in the Service SDK just like the agent posts are.

**Comment by plangstrom** [comment]
@geekandt Before logging a customer support case, please make sure that your custom Apex code use to auto-post to the Chatter feed when a case is created or closed also invokes the trigger needed to send the push notification.
