### ISSUE TITLE
Is it possible to customise how the chat interface is minimized?

### ISSUE THREAD

**Issue by JeanAzzopardi** [forcedotcom/ServiceSDK-iOS#82]
Hi, we're exploring the use of this sdk in our app, and it's working quite well. Our only issue is that the minimized interface clashes with the style of the app, where we already have a custom minimizing interface.

Is it possible for us to do this without rewriting the entire chat interface, i.e. the SCSChatViewController?

We've noticed the `SCSMinimizable` protocol but it seems that the SCSChatInterface doesn't conform to it?

**Comment by aeisses** [comment]
Hey Jean,

Not 100% what you are trying to do... if you are trying to disable the minimized view that is done through the SCSChatConfiguration (http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/220.0/Classes/SCSChatConfiguration.html) not with the SCSMinimizable protocol.

If you are looking at doing some branding of the minimized view we have some options for this:
https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/servicesdk_ui_customization.htm

Sorry for the slow response, yesterday was a holiday in Canada, if you have any other questions please reach out,
Aaron

**Comment by JeanAzzopardi** [comment]
Hi @aeisses, sorry I didn't get my point across correctly. I'd like to customise the interface specifically of the minimized view - not just disable minimization. E.g. I'd like to customise the entire view for that. Can I do that while keeping the same view for the un-minimized chat, i.e. the SCSChatViewController?

Or do I have to write the entire interface from scratch following this link? https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/live_agent_chat_core_api.htm

Just want to get an idea of how much work is required, that's all.

Thanks,
Jean

**Comment by aeisses** [comment]
Hey Jean,

We do not give the option to just customize the minimized view. You need to write the entire interface from scratch.

If you have any other questions, let me know.

Thanks,
Aaron
