### ISSUE TITLE
Starting a session with ChatCore still shows the UI

### ISSUE THREAD

**Issue by psm14** [forcedotcom/ServiceSDK-iOS#83]
### Issue description
I'm trying to implement a custom UI on top of the chat SDK, as documented [here](https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/live_agent_chat_core_api.htm), and the SDK's chat UI still appears anyway when starting a session.

### Reproduction steps
This can be trivially reproduced in the example app. Simply modify the `startChat` function in `ViewController.swift` like so:

```
  /**
   Starts Live Agent Chat.
   */
  @IBAction func startChat(_ sender: Any) {
    ServiceCloud.shared().chatCore.startSession(with: SnapinsConfig.instance.chatConfig!)
  }
```

### Version of SDK components being used
I cloned this repo at commit 0068bbc592c5add53d69cf5026f49db48098cb4f to reproduce, and used version 220.0.0 of the ServiceSDK.

### Device(s) and version(s) of iOS being used
It happens on my iPhone Xs as well as the simulator.

### Screenshots / Videos
Here is a screenshot of the example app in the simulator showing the minimized pop-up window despite the session being started through `chatCore`:

![Simulator Screen Shot - iPhone Xs - 2019-05-28 at 15 09 46](https://user-images.githubusercontent.com/934660/58505370-c560b580-815a-11e9-8248-ab52a40d8643.png)

Note that this is also with `SnapinsConstants.ENABLE_PRECHAT_FIELDS` set to `false`.

**Comment by aeisses** [comment]
Hey @psm14 

Thanks for bringing this to our attention, we are looking into this issue.

Aaron

**Comment by aeisses** [comment]
@psm14 

A fix for this bug will be in the next major release.

Thanks,
Aaron

**Comment by YamibuyJson** [comment]
I have the same problem.

**Comment by kcshiqi** [comment]
Hi @aeisses,

Is this issue fixed? As I am having the same issue as well ...
