### ISSUE TITLE
iOS Push notification issue - Auto-response Notification not sent on first SF login

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-iOS#84]
Issue description
We can't receive push notification for the new users who log a case for the first time. We have known about this issue since the beginning so we should be able to reproduce this on all iOS devices across all SF Service SDKs.

EXPECTED RESULT/UX 
* I should receive a Push Notification within seconds, for the auto-response to the case I just opened 

ACTUAL RESULT/UX (bug) 
* I do NOT receive a Push Notification at all, for the auto-response to the case I just opened 

Reproduction steps
1.  I open the iOS app (any version) 
2. I authenticate as a new user (or an existing user) 
3. The first time I press "Get in touch” button from More screen (i.e. Log in to SF for the first time) 
4. I see Empty Case screen 
5. I open a new case and fill in all mandatory fields 
6. Click Submit
*** No push notification received****

NOTE (continuation from the steps above) 

1. I kill the app 
2. I press “Get in touch” button again, i.e. I re-enter the Case screen (now with 1 case) 
3. I open a new case 
4. I will now receive a Push Notification for the case I just opened 

Version of SDK components being used
- All SDK version

 Device(s) and version(s) of iOS being used
- All devices and versions

**Comment by aeisses** [comment]
@shanecinense1994 

Thanks for bringing this to our attention. We will look into it.

Thanks,
Aaron

**Comment by shanecinense1994** [comment]
Thanks @aeisses , We're looking forward for any updates.

**Comment by shanecinense1994** [comment]
Hi @aeisses , is there any update with this issue? Thank you

**Comment by aeisses** [comment]
Hey @shanecinense1994 

We are looking into this issue. We will get back to you when we know more information.

Aaron

**Comment by shanecinense1994** [comment]
Thanks @aeisses

**Comment by aeisses** [comment]
@shanecinense1994 

Push notification issues are tough on the mobile side. You need to open a case with our main support line. The issue is probably with the APEX trigger on the server, the mobile team has no visibility to the APEX triggers.

If you want to get a resolution you need to open a support case: https://help.salesforce.com/home.

Sorry this is taking so long, but it is WWDC week and a lot is going on.

Thanks,
Aaron
