### ISSUE TITLE
ServiceCore.framework/prepare-framework is broken on macOS Catalina

### ISSUE THREAD

**Issue by Argent** [forcedotcom/ServiceSDK-iOS#87]
Please fill out the following details:

When trying to run the build step: "$SRCROOT/Frameworks/SalesForce/ServiceCore.framework/prepare-framework" on macOS Catalina the script breaks with a system message saying:

“ServiceCore.framework” is damaged and can’t be opened. You should move it to the Bin.

<img width="488" alt="Screenshot 2019-06-07 at 07 31 45" src="https://user-images.githubusercontent.com/717301/59084435-80c3df80-88fb-11e9-8c58-5e0ae893a750.png">

- Version of Mobile SDK Used:
220.1.0
- OS Version:
iOS - macOS Catalina (10.15 Beta (19A471t))
- Steps to reproduce:
Run the prepare-framework script

**Comment by aeisses** [comment]
Hey @Argent,

Thanks for bringing this to our attention. We are starting our testing on macOS Catalina and iOS 13.

Thanks,
Aaron
