### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ServiceSDK/Chat"

### ISSUE THREAD

**Issue by adrianortuzar** [forcedotcom/ServiceSDK-iOS#88]
Following those instructions: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_install_sdk_cocoapods.htm

My pod version: `pod --version 1.7.1`

This is the pod file

```
platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

target 'myTarget' do
    pod 'ServiceSDK/Chat'
end
```

This is the error when I run 'pod install --repo-update'

```
CocoaPods could not find compatible versions for pod "ServiceSDK/Chat":
  In Podfile:
    ServiceSDK/Chat
```
I also tried `pod deintegrate` before

When I run `pod repo update --verbose`

```
CDN: goinstant Relative path couldn't be downloaded: CocoaPods-version.yml Response: 404

Updating spec repo `goinstant`

Updating spec repo `master`
```
This is the podspec from ServiceSDK https://github.com/CocoaPods/Specs/blob/master/Specs/3/1/e/ServiceSDK/1.1.0/ServiceSDK.podspec.json

**Comment by aeisses** [comment]
Hey @adrianortuzar,

The podspec you linked is not the ServiceSDK.podspec, I am not sure where that came from. It looks like you have some issues in your Podfile.

The ServiceSDK only supports iOS 10. You will need to update that to ```platform :ios '10.0'```.
You do not need the ```use_frameworks!```, the podspec will deliver frameworks.
You can remove the 
```source 'https://github.com/CocoaPods/Specs.git'
```
if you are only using the ServiceSDK framework.

Try those out and let me know how it works,

Aaron

**Comment by adrianortuzar** [comment]
Thanks @aeisses, but no luck with your recommendations. Still same issue.

You can find the podspec for ServiceSDK here https://cocoapods.org/pods/ServiceSDK

**Comment by aeisses** [comment]
Hey @adrianortuzar 

That is not our Podspec. Someone has created another Podspec of the same name, which is fine. We do not have a monopoly on names.

Our Podspec is not hosted on with CocoaPods. We host our own Podspec. Here is the link:
https://github.com/goinstant/pods-specs-public/blob/master/ServiceSDK/220.1.0/ServiceSDK.podspec

If you use the following Podfile this will work:
```
source 'https://github.com/goinstant/pods-specs-public'

target 'myTarget' do
  pod 'ServiceSDK/Chat'
end
```

This works without issue. If you are having further issue with your CocoaPod environment I would suggest you reach out to the CocoaPods team.

Thanks,
Aaron

**Comment by adrianortuzar** [comment]
I paste here the error. I think the error is in the goinstant repo.

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10'
use_frameworks!

source 'https://github.com/goinstant/pods-specs-public'

target 'myProject' do
    pod 'ServiceSDK', '~> 216.0.0'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/myuser/.cocoapods/repos/goinstant/all_pods_versions.txt
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/cdn_source.rb:266:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/cdn_source.rb:266:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/cdn_source.rb:266:in `local_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/cdn_source.rb:243:in `ensure_versions_file_loaded'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/cdn_source.rb:177:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:389:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:358:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:332:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:139:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:248:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:88:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/command/update.rb:62:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by ciprianiloc** [comment]
I have the same error :(

**Comment by adrianortuzar** [comment]
Until this is fix, I am adding the ServiceSDK framework manually to Xcode.

**Comment by aeisses** [comment]
@adrianortuzar @ciprianiloc I checked around with my co-workers and was able to repo your issue.

It is something messed up with your cocoapods locally on your machines. Execute the following commands and it will fix your problem.
```
pod repo remove goinstant
pod repo add goinstant https://github.com/goinstant/pods-specs-public
pod update
```

Let me know if this fixes your issue.

Thanks,
Aaron

**Comment by ciprianiloc** [comment]
@aeisses  for me it worked OK. 
Thanks, 
Ciprian

**Comment by adrianortuzar** [comment]
@aeisses works, thanks for the solutions. 

Still the `pod install` does not clone correctly the goinstant repo.

**Comment by aeisses** [comment]
@adrianortuzar I am not sure why that is not working. I might be an issue with the latest version of Cocoapods or the ServiceSDK podspec that does not belong to Salesforce. The ServiceSDK podspec has been live for several years, we have never had a problem.

**Comment by ScottRobbins** [comment]
@aeisses 

So this doesn't work for me either or several at our office (basically everyone who is just setting up the project). Your steps work, but I'm curious if you have reached out to cocoapods about this?

**Comment by aeisses** [comment]
@ScottRobbins We have not, we might need to do that if this issue continues.

**Comment by cristianbanarescu** [comment]
> @adrianortuzar @ciprianiloc I checked around with my co-workers and was able to repo your issue.
> 
> It is something messed up with your cocoapods locally on your machines. Execute the following commands and it will fix your problem.
> 
> ```
> pod repo remove goinstant
> pod repo add goinstant https://github.com/goinstant/pods-specs-public
> pod update
> ```
> 
> Let me know if this fixes your issue.
> 
> Thanks,
> Aaron

Hello, @aeisses ! Your solution also worked for me, with an exception: i am using fastlane in my project and in the fastfile, in the before_all lane i used the 'cocoapods' call, so this caused me a problem. After adding those 3 commands from you, fastlane was then running pod install ( from cocoapods call ) and this messed up my pods again :( I commented out the cocoapods call and everything worked smoothly. Thanks again and i hope i can also help other people who also might had this kind of problem!
