### ISSUE TITLE
Error installing ServiceSDK

### ISSUE THREAD

**Issue by ciprianiloc** [forcedotcom/ServiceSDK-iOS#89]
Hello, 
I followed the instructions: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_install_sdk_cocoapods.htm

My pod version is: 1.7.1

This is what I have in my podfile:

> platform :ios, '10.0'
> use_frameworks!
> 
> source 'https://github.com/CocoaPods/Specs.git'
> source 'https://github.com/goinstant/pods-specs-public'
> 
> target 'myTarget' do
>     pod 'ServiceSDK'
> end

I receive the next error : 

> [!] Error installing ServiceSDK
> [!] /usr/local/bin/git clone https://github.com/ninhnm/ServiceSDK.git /var/folders/xy/_98f1tbn1t185kzbp5wbvn100000gn/T/d20190613-93300-43ixsx --template= --single-branch --depth 1 --branch 1.1.0
> 
> Cloning into '/var/folders/xy/_98f1tbn1t185kzbp5wbvn100000gn/T/d20190613-93300-43ixsx'...
> remote: Repository not found.
> fatal: repository 'https://github.com/ninhnm/ServiceSDK.git/' not found

**Comment by adrianortuzar** [comment]
We have the same issue https://github.com/forcedotcom/ServiceSDK-iOS/issues/88

**Comment by aeisses** [comment]
Hey @ciprianiloc 

I am not sure what is going on in your Cocoapod environment, but the Podspec reference in your error is not the Salesforce ServiceSDK Podspec. Our Podspec is hosted here:
https://github.com/goinstant/pods-specs-public/blob/master/ServiceSDK/220.1.0/ServiceSDK.podspec

If you use the following Podfile this will work:
```
source 'https://github.com/goinstant/pods-specs-public'

target 'myTarget' do
  pod 'ServiceSDK/Chat'
end
```
This works without issue. If you are having further issue with your CocoaPod environment I would suggest you reach out to the CocoaPods team.

Thanks,
Aaron

**Comment by aeisses** [comment]
Duplicate: https://github.com/forcedotcom/ServiceSDK-iOS/issues/88
