### ISSUE TITLE
iOS Chat Customization: images not set

### ISSUE THREAD

**Issue by fermoya** [forcedotcom/ServiceSDK-iOS#9]
Hi, 

I'm using the release 208.6.0 for iOS and trying to customize the chat images when both minimized and expanded. My goal is to have something similar to the result you get with Android SDK. On the attached files you can see the how it looks like in Android, I've remarked in red the image I wanna set/change.

![device-2017-10-25-100901](https://user-images.githubusercontent.com/11335612/31988143-5d910352-b96e-11e7-9fd1-2eb34eda60d4.png)
![device-2017-10-25-100925](https://user-images.githubusercontent.com/11335612/31988144-5da84774-b96e-11e7-8fcb-b6c251aec89b.png)

By default, this image is included and shows up when using Android SDK so I don't understand why the behavior isn't similar in iOS. Consequently, I tried to set the image myself by using with the following code:

`let appearance = SCAppearanceConfiguration();`
`appearance.setImage(UIImage(named: "myContactImage")!, compatibleWith: self.traitCollection, forName: "ChatIcon") // I've also tried with "ChatAgentAvatar" and "PreChatIcon"`

`SCServiceCloud.sharedInstance().appearanceConfiguration = appearance;`

`SCServiceCloud.sharedInstance().chat.determineAvailability(with: chatConfig) { [weak self](error, available) in`
`	if (error != nil && available) { SCServiceCloud.sharedInstance().chat.startSession(with: self?.chatConfig) }`
`}`

Nonetheless with this code the result is the following:

![captura de pantalla 2017-10-25 a las 10 30 20](https://user-images.githubusercontent.com/11335612/31988516-b1136c8a-b96f-11e7-9789-2b193fbf75ef.png)

Which is not what I want. I've also tried with "ChatAgentAvatar" and "PreChatIcon" but they don't seem to change anything. Other customizable images do work like "Close" or "MinimizeButtonImage".

Am I doing anything wrong? Am I assuming something it isn't? The image I'm using for all of them is:
- 1x --> 27x27
- 2x --> 54x54

Thanks in advance

**Comment by tmyrden** [comment]
@fermoya The icon you're looking for on iOS is `ChatAgentAvatar`. Unfortunately, there was a bug with setting that image on the version of the SDK that's currently in your hands. We should have the new version up very soon for you to consume and this will be fixed!

**Comment by tmyrden** [comment]
@fermoya As a quick workaround for you, try using `nil` instead of `self.traitCollection`

**Comment by fermoya** [comment]
That works, thank you so much!
