### ISSUE TITLE
Can't set initialValue in SCSPrechatTextInputObject

### ISSUE THREAD

**Issue by Sonasi986** [forcedotcom/ServiceSDK-iOS#90]
### Issue description
When I try to use a SCSPrechatTextInputObject, I can't set an initialValue as Android developers can with the _ServiceSDK-Android_.
Even using
```Swift
let test = SCSPrechatTextInputObject(label: "AB", value: "CD")

// or

let test = SCSPrechatTextInputObject(label: "AB")
test.value = "CD"
```
The prechat field "AB" is still empty.

**Or** on Android they have a method called "initialValue" allowing them to prefill any textfield.

```Java
PreChatTextInputField.Builder()
                        .required(true)
                        .inputType(EditorInfo.TYPE_CLASS_TEXT)
                        .initialValue("CD")
                        .build("AB", "AB");
```

### Version of SDK components being used
Version 220.1.0 (Using Cocoapods)

**Comment by MikeNachbaur** [comment]
I've reproduced this locally, and have created a ticket internally to track this issue. Thank you for bringing this to our attention.

**Comment by aeisses** [comment]
@Sonasi986 A fix for this bug will be in the next major release.

Thanks for pointing this out to us,
Aaron

**Comment by salvattore315** [comment]
Hello @aeisses how are you? I would like to know if this issue is relese in some version?

**Comment by aeisses** [comment]
@salvattore315 The update with this fix has not been released yet.

It will be released in October.

Thanks,
Aaron
