### ISSUE TITLE
Setting navbarBackground using SCAppearanceConfiguration is not working

### ISSUE THREAD

**Issue by Sonasi986** [forcedotcom/ServiceSDK-iOS#91]
### Issue description
Hello, we're trying to change the navbarBackground of the Chat but it is not working, the color of the navbarBackground still the same as the ViewController from where the chat is launch.

### Reproduction steps

Create a ViewController in a NavigationController with for example a red NavigationBar then add a button which call the following code :

```Swift
let serviceCloud = ServiceCloud.shared()
let appearance = SCAppearanceConfiguration()
appearance.setColor(.white, forName: .navbarBackground)
serviceCloud.appearanceConfiguration = appearance
serviceCloud.chatUI.showChat(with: configuration) // Let's imagine configuration is already perfectly created and filled.
```

Let's run the code and click on the button. The NavigationBar background of the chat is still red.

### Version of SDK components being used
Version 220.1.0 (Using Cocoapods)

### Device(s) and version(s) of iOS being used
iPhone X & XS running iOS 12.0

**Comment by MikeNachbaur** [comment]
It's recommended that you only apply the appearance configuration once in the lifetime of your application, either at app launch, or when your SDK configuration is applied.

Also, are you using UIAppearance within your application for configuring the style of your application?

**Comment by Sonasi986** [comment]
@MikeNachbaur Hello, I apply the appearance configuration only one time in the lifetime of my application.

We do not use UIAppearance.

**Comment by MikeNachbaur** [comment]
Thank you for the extra information @Sonasi986, we'll take a look at this and will get back to you as soon as we can.

**Comment by MikeNachbaur** [comment]
One further question: when you say the navigation bar starts out as red, how are you doing this specifically? And is the chat view controller being pushed onto your existing navigation stack, or is it being presented full-screen?

**Comment by aeisses** [comment]
The customer has stopped communicating on this issues and we can not reproduce it. Closing the ticket.
