### ISSUE TITLE
Can't reopen the chat after a message

### ISSUE THREAD

**Issue by Sonasi986** [forcedotcom/ServiceSDK-iOS#94]
### Issue description
I open the chat and send a message to an agent. I reduce the window and move on my application. Then I expands the chat and close it.

When I try to reopen it, it does not open anymore.

The button to open the chat is in a Modal.

### Version of SDK components being used
Version 220.1.0 (Using Cocoapods)

**Comment by aeisses** [comment]
Hey @Sonasi986,

Not sure exactly what you are seeing, can you provide some more information or even a video?

Thanks,
Aaron

**Comment by aeisses** [comment]
Since no response has been given to this ticket and we can not reproduce the issue it is being closed.
