### ISSUE TITLE
iOS Connection Token is not generating on the first app launch

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-iOS#97]
### Issue description:
On the first launch of our app, connection token was not automatically generated. However, when we kill the app and tried to create another case, connection token is created.

### Reproduction steps
This is for the authenticated users:

1. Create a new user.
2. Create a case.
3. No connection token created.
4. Kill the app.
5. Create a new case.
6. Connection token was created.

Actual: No connection token created on the first app launch.
Expected: There should be a connection token created on the first app launch.

### Device(s) and version(s) of iOS being used
iOS Device: iPhone 6S Plus
iOS Version: 12.1.4

### Screenshots / Videos

Actual
![image](https://user-images.githubusercontent.com/45929577/61017909-81063d80-a3c7-11e9-814b-5ffe1e6c8822.png)

Expected
![image](https://user-images.githubusercontent.com/45929577/61018014-df332080-a3c7-11e9-8696-a9b51aac7b05.png)

### Additional Questions:
1. Is there a callback or response from the Mobile SDK, when SF successfully receives and updates the Connection Token?
2. We can try to increase the number of times the app tries to call the SDK to update the Connection Token - for example, app could attempt to do this when the user backgrounds the app, or leaves the Salesforce Case List page to another app screen. However we would like to know if we substantial increase the number of API calls, will this have any adverse impact?

**Comment by aeisses** [comment]
Hey @shanecinense1994,

I did a quick test and I am able to see the connection token in my org when I execute the following steps:
- Start the cases app
- Login the user
The token is created.

The token should be created when the user logs in with the Mobile SDK, not when a case is created.

Could you provide a little clarity on the steps you are taking?

Thanks,
Aaron

**Comment by shanecinense1994** [comment]
Hi @aeisses ,

Yes that's correct. The connection token was generated upon user's first login. However, this is only being generated/added on the app side but not on the SF Mobile Push Registration that's why our push notifications are not working on user's first login.

Connection token was being added in SF Mobile Push Registration on the second log in of user on the app. In this situation, user will never receive the (automated) acknowledgement or the ad hoc reply to their initial problems when their creating a case.

Steps:
1. Open app
2. Create User
Result: Connection token was generated on the app side but not on the SF Mobile Push Registration

3. Kill the app
4. Open app
5. Log in
Result: Connection token was now added on the SF Mobile Push Registration

In line with this, we need to confirm and ask why did the connection token not being generated in SF Mobile Push Notification on user's first log in?

Thank you

**Comment by aeisses** [comment]
@shanecinense1994 

This appears to be a MobileSDK issue. The Cases SDK can use the MobileSDK for authentication. That is a different team at Salesforce. You can open an issue here or see if they already have an existing issue:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS

Thanks,
Aaron

**Comment by aeisses** [comment]
@shanecinense1994 Something here might be helpful to you:

https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_ios_code.htm

**Comment by shanecinense1994** [comment]
Thanks @aeisses 

We have open a new ticket on the Mobile SDK team.
