### ISSUE TITLE
How can I get String Value from ServiceChatString Constants

### ISSUE THREAD

**Issue by Maxwell6635** [forcedotcom/ServiceSDK-iOS#98]
I want to get string value from this string constants to display. 
http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/220.1/servicechatstringconstants.html

**Comment by aeisses** [comment]
Hey @Maxwell6635, 

This is more of a general iOS programing question than a ServiceSDK question, so I am going to point you to the Apple Docs for this: 
https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html

The bundle identifier for the Chat SDK is: "com.salesforce.ServiceSDK.Chat"

Thanks,
Aaron
